import { StyleSheet } from 'react-native';

export const BRAND_PURPLE = '#5A2D82';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  headerTitle: {
    fontSize: 18,
    fontFamily: 'Inter-Bold',
    color: '#1F2937',
  },
  closeButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#F3F4F6',
    justifyContent: 'center',
    alignItems: 'center',
  },
  scrollView: {
    flex: 1,
  },
  imageGalleryContainer: {
    position: 'relative',
    backgroundColor: '#F3EFF7',
  },
  imageSkeleton: {
    width: '100%',
    height: 300,
    backgroundColor: '#E8E3EB',
  },
  imageGallery: {
    width: '100%',
    height: 300,
  },
  galleryImage: {
    height: 300,
  },
  productImage: {
    width: '100%',
    height: 300,
  },
  imageNavButton: {
    position: 'absolute',
    top: '50%',
    transform: [{ translateY: -20 }],
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  prevButton: {
    left: 16,
  },
  nextButton: {
    right: 16,
  },
  imageIndicators: {
    position: 'absolute',
    bottom: 16,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
  },
  imageIndicator: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: 'rgba(255, 255, 255, 0.5)',
  },
  imageIndicatorActive: {
    backgroundColor: '#FFFFFF',
  },
  productInfo: {
    padding: 20,
  },
  productName: {
    fontSize: 24,
    fontFamily: 'Inter-Bold',
    color: '#1F2937',
    marginBottom: 8,
  },
  productPrice: {
    fontSize: 20,
    fontFamily: 'Inter-Bold',
    color: '#5A2D82',
    marginBottom: 8,
  },
  ratingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    gap: 4,
  },
  starRating: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  ratingText: {
    fontSize: 14,
    fontFamily: 'Inter-Medium',
    color: '#6B7280',
    marginLeft: 4,
  },
  productDescription: {
    fontSize: 16,
    fontFamily: 'Inter-Regular',
    color: '#6B7280',
    lineHeight: 24,
    marginBottom: 12,
  },
  stockText: {
    fontSize: 14,
    fontFamily: 'Inter-Medium',
    color: '#10B981',
  },
  urgencyPill: {
    alignSelf: 'flex-start',
    backgroundColor: '#FEF3C7',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 7,
    marginTop: 2,
  },
  urgencyPillText: {
    color: '#B45309',
    fontFamily: 'Inter-SemiBold',
    fontSize: 13,
  },
  rewardNudge: {
    marginTop: 12,
    borderRadius: 12,
    backgroundColor: '#F3EFF7',
    borderWidth: 1,
    borderColor: '#E6DDEF',
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  rewardNudgeDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#FDB813',
    shadowColor: '#FDB813',
    shadowOpacity: 0.45,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 0 },
    elevation: 2,
  },
  rewardNudgeTitle: {
    color: '#32154E',
    fontFamily: 'Inter-Bold',
    fontSize: 13,
  },
  rewardNudgeText: {
    marginTop: 2,
    color: '#665F6C',
    fontFamily: 'Inter-Regular',
    fontSize: 12,
    lineHeight: 17,
  },
  selectionSection: {
    paddingHorizontal: 20,
    marginBottom: 24,
  },
  selectionTitle: {
    fontSize: 16,
    fontFamily: 'Inter-SemiBold',
    color: '#1F2937',
    marginBottom: 12,
  },
  soldText: { fontSize: 13, fontFamily: 'Inter-Medium', color: '#7A7380' },
  priceRow: { flexDirection: 'row', alignItems: 'center', gap: 8, flexWrap: 'wrap' },
  comparePrice: { fontSize: 15, fontFamily: 'Inter-Regular', color: '#9CA3AF', textDecorationLine: 'line-through' },
  discountBadge: { backgroundColor: '#EF4444', borderRadius: 6, paddingHorizontal: 7, paddingVertical: 2 },
  discountBadgeText: { color: '#FFFFFF', fontFamily: 'Inter-Bold', fontSize: 12 },
  optionButtonSoldOut: { opacity: 0.45, borderColor: '#E5E7EB' },
  optionTextSoldOut: { color: '#9CA3AF', textDecorationLine: 'line-through' },
  sizeLeft: { fontSize: 10, fontFamily: 'Inter-SemiBold', color: '#EF4444', marginTop: 2 },
  logoUploadBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, borderWidth: 1.5, borderColor: BRAND_PURPLE, borderStyle: 'dashed', borderRadius: 12, minHeight: 52 },
  logoUploadText: { fontSize: 14, fontFamily: 'Inter-SemiBold', color: BRAND_PURPLE },
  logoPreviewWrap: { alignSelf: 'flex-start' },
  logoPreview: { width: 120, height: 120, borderRadius: 12, backgroundColor: '#F3F4F6' },
  logoRemove: { position: 'absolute', top: -8, right: -8, width: 26, height: 26, borderRadius: 13, backgroundColor: '#17131C', alignItems: 'center', justifyContent: 'center' },
  sizeHeaderRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 12 },
  sizeGuideLink: { fontSize: 13, fontFamily: 'Inter-SemiBold', color: BRAND_PURPLE },
  trustCard: { marginTop: 16, backgroundColor: '#F9F7FB', borderRadius: 12, borderWidth: 1, borderColor: '#EDEAF1', paddingHorizontal: 14 },
  trustRow: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: '#EDEAF1' },
  trustRowLast: { borderBottomWidth: 0 },
  trustText: { flex: 1, fontSize: 13.5, fontFamily: 'Inter-Medium', color: '#374151' },
  sizeGuideContainer: { flex: 1, backgroundColor: '#FFFFFF' },
  sizeGuideHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 20, paddingVertical: 16, borderBottomWidth: 1, borderBottomColor: '#E5E7EB' },
  sizeGuideTitle: { fontSize: 20, fontFamily: 'Inter-Bold', color: '#1F2937' },
  sizeGuideCloseBtn: { width: 40, height: 40, borderRadius: 20, backgroundColor: '#F3F4F6', alignItems: 'center', justifyContent: 'center' },
  sizeGuideNote: { fontSize: 13, fontFamily: 'Inter-Regular', color: '#6B7280', lineHeight: 19, marginBottom: 16 },
  sizeGuideSection: { fontSize: 15, fontFamily: 'Inter-Bold', color: '#17131C', marginTop: 8, marginBottom: 8 },
  sgTable: { borderWidth: 1, borderColor: '#EDEAF1', borderRadius: 10, overflow: 'hidden', marginBottom: 20 },
  sgRow: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: '#F0EDF4' },
  sgHead: { backgroundColor: '#F6F1FB' },
  sgCell: { flex: 1, paddingVertical: 11, paddingHorizontal: 10, fontSize: 13, fontFamily: 'Inter-Regular', color: '#374151', textAlign: 'center' },
  sgHeadText: { fontFamily: 'Inter-Bold', color: '#17131C' },
  sgCellBold: { fontFamily: 'Inter-Bold', color: BRAND_PURPLE },
  returnsSupportBtn: { marginTop: 18, backgroundColor: BRAND_PURPLE, borderRadius: 10, minHeight: 48, alignItems: 'center', justifyContent: 'center' },
  returnsSupportBtnText: { color: '#FFFFFF', fontFamily: 'Inter-SemiBold', fontSize: 15 },
  noteHint: {
    fontSize: 13,
    fontFamily: 'Inter-Regular',
    color: '#6B7280',
    marginBottom: 8,
  },
  noteInput: {
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 14,
    fontFamily: 'Inter-Regular',
    color: '#1F2937',
    minHeight: 84,
    backgroundColor: '#FFFFFF',
  },
  optionsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  optionButton: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    backgroundColor: '#FFFFFF',
    minWidth: 80,
    alignItems: 'center',
    position: 'relative',
  },
  optionButtonActive: {
    backgroundColor: '#5A2D82',
    borderColor: '#5A2D82',
  },
  checkIcon: {
    position: 'absolute',
    top: 4,
    right: 4,
  },
  optionText: {
    fontSize: 14,
    fontFamily: 'Inter-Medium',
    color: '#1F2937',
  },
  optionTextActive: {
    color: '#FFFFFF',
  },
  quantityContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  quantityButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#5A2D82',
    justifyContent: 'center',
    alignItems: 'center',
  },
  quantityText: {
    fontSize: 18,
    fontFamily: 'Inter-Bold',
    color: '#1F2937',
    minWidth: 40,
    textAlign: 'center',
  },
  summarySection: {
    marginHorizontal: 20,
    backgroundColor: '#F3F4F6',
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
  },
  summaryTitle: {
    fontSize: 16,
    fontFamily: 'Inter-SemiBold',
    color: '#1F2937',
    marginBottom: 8,
  },
  summaryText: {
    fontSize: 14,
    fontFamily: 'Inter-Regular',
    color: '#6B7280',
    marginBottom: 4,
  },
  summaryPrice: {
    fontSize: 16,
    fontFamily: 'Inter-Bold',
    color: '#5A2D82',
  },
  reviewsSection: {
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  bottomSection: {
    padding: 20,
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
  },
  cartError: { color: '#912018', backgroundColor: '#FEF3F2', borderRadius: 8, padding: 10, fontFamily: 'Inter-Regular', fontSize: 12, lineHeight: 18, marginBottom: 10 },
  addToCartButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#5A2D82',
    borderRadius: 12,
    paddingVertical: 16,
    gap: 8,
  },
  addToCartButtonDisabled: {
    opacity: 0.5,
  },
  addToCartText: {
    fontSize: 16,
    fontFamily: 'Inter-SemiBold',
    color: '#FFFFFF',
  },
  previewModalOverlay: {
    flex: 1,
    backgroundColor: '#0B0910',
  },
  previewHeader: {
    minHeight: 72,
    paddingHorizontal: 20,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  previewTitle: {
    color: '#FFFFFF',
    fontSize: 17,
    lineHeight: 22,
    fontFamily: 'Inter-SemiBold',
  },
  previewCounter: {
    marginTop: 2,
    color: '#CFC8D5',
    fontSize: 13,
    lineHeight: 18,
    fontFamily: 'Inter-Regular',
  },
  previewCloseButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  previewImageContainer: {
    width: '100%',
    overflow: 'hidden',
  },
  previewPage: {
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 12,
  },
  previewImage: {
    width: '100%',
    height: '100%',
  },
  previewHint: {
    minHeight: 48,
    paddingHorizontal: 20,
    paddingTop: 12,
    color: '#CFC8D5',
    textAlign: 'center',
    fontSize: 13,
    lineHeight: 18,
    fontFamily: 'Inter-Regular',
  },
  // How to order guide (in-tree overlay covering the product modal)
  htoOverlay: {
    position: 'absolute',
    top: 0, left: 0, right: 0, bottom: 0,
    zIndex: 1000,
    backgroundColor: 'rgba(17, 24, 39, 0.55)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  htoCard: {
    width: '100%',
    maxWidth: 420,
    maxHeight: '86%',
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    padding: 20,
    shadowColor: '#000000',
    shadowOpacity: 0.2,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 12 },
    elevation: 14,
  },
  htoHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F0EDF4',
    marginBottom: 8,
  },
  htoHeaderIcon: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: BRAND_PURPLE,
    alignItems: 'center',
    justifyContent: 'center',
  },
  htoTitle: { fontSize: 18, fontFamily: 'Inter-Bold', color: '#17131C' },
  htoSubtitle: { fontSize: 12.5, fontFamily: 'Inter-Regular', color: '#7A7380', marginTop: 2 },
  htoClose: { width: 30, height: 30, borderRadius: 15, backgroundColor: '#F5F3F7', alignItems: 'center', justifyContent: 'center' },
  htoScroll: { flexGrow: 0 },
  htoStep: { flexDirection: 'row', gap: 12 },
  htoStepLeft: { alignItems: 'center', width: 26 },
  htoBadge: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: '#F0EAF7',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
  },
  htoBadgeText: { fontSize: 12.5, fontFamily: 'Inter-Bold', color: BRAND_PURPLE },
  htoLine: { flex: 1, width: 2, backgroundColor: '#EFEBF4', marginTop: 4, marginBottom: -4 },
  htoStepBody: { flex: 1, paddingTop: 8, paddingBottom: 12 },
  htoStepTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 7, marginBottom: 3 },
  htoStepTitle: { fontSize: 14.5, fontFamily: 'Inter-SemiBold', color: '#17131C' },
  htoStepText: { fontSize: 13, lineHeight: 19, fontFamily: 'Inter-Regular', color: '#5C5563' },
  htoDelivery: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    backgroundColor: '#F7F4FB',
    borderRadius: 12,
    padding: 12,
    marginTop: 4,
    marginBottom: 4,
  },
  htoDeliveryText: { flex: 1, fontSize: 12.5, lineHeight: 18, fontFamily: 'Inter-Medium', color: '#4A4451' },
  htoPrimary: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: BRAND_PURPLE,
    borderRadius: 14,
    minHeight: 52,
    marginTop: 14,
  },
  htoPrimaryText: { color: '#FFFFFF', fontSize: 15, fontFamily: 'Inter-Bold' },
  htoCancel: { alignItems: 'center', paddingVertical: 12, marginTop: 2 },
  htoCancelText: { color: '#7A7380', fontSize: 14, fontFamily: 'Inter-SemiBold' },

  cartConfirmationOverlay: {
    flex: 1,
    backgroundColor: 'rgba(17, 24, 39, 0.45)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  cartConfirmationCard: {
    width: '100%',
    maxWidth: 420,
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 24,
    shadowColor: '#000000',
    shadowOpacity: 0.18,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 12,
  },
  cartConfirmationTitle: {
    fontSize: 22,
    fontFamily: 'Inter-Bold',
    color: '#1F2937',
    marginBottom: 8,
  },
  cartConfirmationMessage: {
    fontSize: 15,
    lineHeight: 22,
    fontFamily: 'Inter-Regular',
    color: '#4B5563',
    marginBottom: 20,
  },
  cartConfirmationActions: {
    flexDirection: 'row',
    gap: 12,
  },
  cartConfirmationButton: {
    flex: 1,
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cartConfirmationPrimaryButton: {
    backgroundColor: '#5A2D82',
  },
  cartConfirmationSecondaryButton: {
    backgroundColor: '#F3F4F6',
  },
  cartConfirmationButtonText: {
    fontSize: 15,
    fontFamily: 'Inter-SemiBold',
    color: '#FFFFFF',
  },
  cartConfirmationSecondaryButtonText: {
    color: '#1F2937',
  },
});
