import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F9FAFB',
  },
  pageShell: { flex: 1, width: '100%', maxWidth: 1344, alignSelf: 'center', paddingHorizontal: 32 },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 34,
    paddingBottom: 28,
  },
  greeting: {
    fontSize: 10,
    fontFamily: 'Inter-Bold',
    color: '#5A2D82',
    letterSpacing: 1.5,
  },
  adminName: {
    fontSize: 28,
    fontFamily: 'Inter-Bold',
    color: '#17131C',
    marginTop: 5,
    letterSpacing: -0.6,
  },
  headerCopy: { fontSize: 13, fontFamily: 'Inter-Regular', color: '#665F6C', marginTop: 6 },
  viewAllButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: '#5A2D82',
    borderRadius: 10,
    gap: 6,
    minHeight: 42,
    shadowColor: '#32154E',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  viewAllText: {
    fontSize: 12,
    fontFamily: 'Inter-SemiBold',
    color: '#FFFFFF',
  },
  scrollView: {
    flex: 1,
  },
  kpiRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 14, marginBottom: 16 },
  kpiCard: { backgroundColor: '#FFFFFF', borderRadius: 14, padding: 16, borderWidth: 1, borderColor: '#EDEAF1' },
  kpiTop: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between' },
  kpiTitle: { fontSize: 12.5, fontFamily: 'Inter-Medium', color: '#7A7380', flex: 1, paddingRight: 6 },
  kpiIcon: { width: 34, height: 34, borderRadius: 9, alignItems: 'center', justifyContent: 'center' },
  kpiValue: { fontSize: 22, fontFamily: 'Inter-Bold', color: '#17131C', marginTop: 12 },
  chartsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 16, marginBottom: 16 },
  card: { backgroundColor: '#FFFFFF', borderRadius: 16, padding: 18, borderWidth: 1, borderColor: '#EDEAF1' },
  cardTitle: { fontSize: 15, fontFamily: 'Inter-Bold', color: '#17131C' },
  cardBig: { fontSize: 22, fontFamily: 'Inter-Bold', color: '#17131C', marginTop: 10 },
  cardCaption: { fontSize: 12, fontFamily: 'Inter-Regular', color: '#7A7380', marginTop: 2 },
  cardHeaderRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 6 },
  donutWrap: { flexDirection: 'row', alignItems: 'center', gap: 16, marginTop: 12 },
  legend: { flex: 1, gap: 8 },
  legendRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  legendDot: { width: 9, height: 9, borderRadius: 5 },
  legendLabel: { flex: 1, fontSize: 12.5, fontFamily: 'Inter-Medium', color: '#4A4453' },
  legendValue: { fontSize: 12.5, fontFamily: 'Inter-Bold', color: '#17131C' },
  listRow: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 9, borderBottomWidth: 1, borderBottomColor: '#F3F0F6' },
  listThumb: { width: 40, height: 48, borderRadius: 8, backgroundColor: '#F3F4F6' },
  listName: { fontSize: 13.5, fontFamily: 'Inter-SemiBold', color: '#17131C' },
  listSub: { fontSize: 12, fontFamily: 'Inter-Regular', color: '#7A7380', marginTop: 1 },
  listMetric: { fontSize: 12.5, fontFamily: 'Inter-Bold', color: '#5A2D82' },
  lowStockIcon: { width: 30, height: 30, borderRadius: 8, backgroundColor: '#FEF3F2', alignItems: 'center', justifyContent: 'center' },
  lowStockValue: { fontSize: 12.5, fontFamily: 'Inter-Bold', color: '#B42318' },
  statsContainer: {
    marginBottom: 32,
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  statCard: {
    minHeight: 148,
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    padding: 18,
    borderWidth: 1,
    borderColor: '#E8E3EB',
    shadowColor: '#32154E',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 10,
    elevation: 1,
  },
  statIcon: { width: 38, height: 38, borderRadius: 10, alignItems: 'center', justifyContent: 'center', marginBottom: 20 },
  statCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 6,
  },
  statValue: {
    fontSize: 25,
    fontFamily: 'Inter-Bold',
    color: '#17131C',
    flexShrink: 1,
    marginLeft: 6,
    textAlign: 'left',
  },
  statTitle: {
    fontSize: 12,
    fontFamily: 'Inter-Medium',
    color: '#665F6C',
  },
  statSubtitle: {
    fontSize: 10,
    fontFamily: 'Inter-Regular',
    color: '#7A7380',
    marginTop: 2,
  },
  recentOrdersContainer: {
    marginBottom: 24,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 18,
    fontFamily: 'Inter-Bold',
    color: '#17131C',
  },
  seeAllText: {
    fontSize: 14,
    fontFamily: 'Inter-SemiBold',
    color: '#5A2D82',
  },
  ordersCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E8E3EB',
    shadowColor: '#32154E',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 2,
  },
  orderItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  orderInfo: {
    flex: 1,
  },
  customOrderBadge: {
    backgroundColor: '#5A2D8220',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
    alignSelf: 'flex-start',
    marginBottom: 4,
  },
  customOrderText: {
    fontSize: 10,
    fontFamily: 'Inter-SemiBold',
    color: '#5A2D82',
  },
  orderCustomer: {
    fontSize: 14,
    fontFamily: 'Inter-SemiBold',
    color: '#1F2937',
    marginBottom: 2,
  },
  orderId: {
    fontSize: 12,
    fontFamily: 'Inter-Regular',
    color: '#6B7280',
    marginBottom: 2,
  },
  orderDate: {
    fontSize: 12,
    fontFamily: 'Inter-Regular',
    color: '#9CA3AF',
  },
  orderRight: {
    alignItems: 'flex-end',
    gap: 4,
  },
  orderAmount: {
    fontSize: 14,
    fontFamily: 'Inter-Bold',
    color: '#1F2937',
  },
  currencyIndicator: {
    fontSize: 10,
    fontFamily: 'Inter-Regular',
    color: '#5A2D82',
    fontStyle: 'italic',
  },
  statusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
  },
  statusText: {
    fontSize: 10,
    fontFamily: 'Inter-SemiBold',
  },
  orderActions: {
    padding: 4,
  },
  emptyOrders: {
    padding: 40,
    alignItems: 'center',
  },
  emptyText: {
    fontSize: 14,
    fontFamily: 'Inter-Regular',
    color: '#9CA3AF',
  },
  quickActionsContainer: {
    marginBottom: 32,
  },
  quickActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    marginTop: 12,
  },
  actionCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E8E3EB',
    shadowColor: '#32154E',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 2,
  },
  actionText: {
    fontSize: 12,
    fontFamily: 'Inter-Medium',
    color: '#374151',
    marginTop: 8,
    textAlign: 'center',
  },
  sectionEyebrow: { fontSize: 10, fontFamily: 'Inter-Bold', color: '#7A7380', letterSpacing: 1.4, marginBottom: 12 },
  servicesHeader: { flexDirection: 'row', alignItems: 'baseline', justifyContent: 'space-between', marginBottom: 12 },
  sectionHint: { color: '#7A7380', fontFamily: 'Inter-Regular', fontSize: 12 },
  serviceGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 16, marginBottom: 34 },
  serviceCard: { minHeight: 72, flexDirection: 'row', alignItems: 'center', gap: 12, padding: 14, borderRadius: 12, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E8E3EB' },
  serviceIcon: { width: 36, height: 36, borderRadius: 9, alignItems: 'center', justifyContent: 'center' },
  serviceCopy: { flex: 1 },
  serviceTitle: { color: '#3D3742', fontFamily: 'Inter-Medium', fontSize: 12 },
  serviceValue: { color: '#17131C', fontFamily: 'Inter-Bold', fontSize: 17 },
});

export const detailStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0,0,0,0.4)',
  },
  overlayTouchable: {
    flex: 1,
  },
  sheet: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: '80%',
    paddingBottom: 32,
  },
  dragHandle: {
    width: 40,
    height: 4,
    backgroundColor: '#D1D5DB',
    borderRadius: 2,
    alignSelf: 'center',
    marginTop: 12,
    marginBottom: 8,
  },
  sheetHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  sheetTitle: {
    fontSize: 17,
    fontFamily: 'Inter-Bold',
    color: '#1F2937',
  },
  closeBtn: {
    padding: 6,
    borderRadius: 20,
    backgroundColor: '#F3F4F6',
  },
  loadingContainer: {
    paddingVertical: 60,
    alignItems: 'center',
    gap: 12,
  },
  loadingText: {
    fontSize: 14,
    fontFamily: 'Inter-Regular',
    color: '#6B7280',
  },
  emptyContainer: {
    paddingVertical: 60,
    alignItems: 'center',
  },
  emptyText: {
    fontSize: 14,
    fontFamily: 'Inter-Regular',
    color: '#9CA3AF',
  },
  listContent: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 16,
  },
  separator: {
    height: 8,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    backgroundColor: '#F9FAFB',
    borderRadius: 10,
    padding: 12,
  },
  rowLeft: {
    flex: 1,
    marginRight: 12,
    gap: 2,
  },
  rowRight: {
    alignItems: 'flex-end',
    gap: 4,
    minWidth: 80,
  },
  rowPrimary: {
    fontSize: 13,
    fontFamily: 'Inter-SemiBold',
    color: '#1F2937',
  },
  rowSecondary: {
    fontSize: 12,
    fontFamily: 'Inter-Regular',
    color: '#4B5563',
  },
  rowMeta: {
    fontSize: 11,
    fontFamily: 'Inter-Regular',
    color: '#9CA3AF',
  },
  rowAmount: {
    fontSize: 13,
    fontFamily: 'Inter-Bold',
    color: '#1F2937',
  },
  badge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
  },
  badgeText: {
    fontSize: 10,
    fontFamily: 'Inter-SemiBold',
  },
});
