import { StyleSheet } from 'react-native';
import { BRAND_PURPLE, BRAND_GOLD } from './constants';

export const styles = StyleSheet.create({
  catalogFooter: { width: '100%', paddingHorizontal: 16, paddingTop: 8, gap: 28 },
  paginationRow: { width: '100%', maxWidth: 520, alignSelf: 'center', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  pageButton: { minWidth: 100, minHeight: 44, borderWidth: 1, borderColor: BRAND_PURPLE, borderRadius: 8, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 14 },
  pageButtonDisabled: { opacity: 0.4 },
  pageButtonText: { color: BRAND_PURPLE, fontFamily: 'Inter-SemiBold', fontSize: 13 },
  pageIndicator: { color: '#665F6C', fontFamily: 'Inter-Medium', fontSize: 12 },
  billPromo: { width: '100%', maxWidth: 900, alignSelf: 'center', minHeight: 88, backgroundColor: '#32154E', borderRadius: 12, paddingHorizontal: 18, paddingVertical: 16, flexDirection: 'row', alignItems: 'center', gap: 14 },
  billPromoIcon: { width: 42, height: 42, borderRadius: 8, backgroundColor: 'rgba(255,255,255,0.1)', alignItems: 'center', justifyContent: 'center' },
  billPromoText: { flex: 1 },
  billPromoTitle: { color: '#FFFFFF', fontFamily: 'Inter-SemiBold', fontSize: 15 },
  billPromoCopy: { color: 'rgba(255,255,255,0.72)', fontFamily: 'Inter-Regular', fontSize: 12, lineHeight: 17, marginTop: 4 },
  offerOverlay: { flex: 1, backgroundColor: 'rgba(23,19,28,0.58)', justifyContent: 'center', alignItems: 'center', padding: 24 },
  offerDesktopLayer: { position: 'absolute', top: 20, right: 24, width: 420, zIndex: 50 },
  offerModal: { width: '100%', maxWidth: 420, backgroundColor: '#FFFFFF', borderRadius: 16, padding: 24 },
  offerClose: { position: 'absolute', top: 12, right: 12, width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center', backgroundColor: '#F8F7F9' },
  offerEyebrow: { color: BRAND_PURPLE, fontFamily: 'Inter-Bold', fontSize: 11, letterSpacing: 1.4, marginBottom: 10 },
  offerTitle: { color: '#17131C', fontFamily: 'Inter-Bold', fontSize: 24, lineHeight: 30, paddingRight: 30 },
  offerSubtitle: { color: '#665F6C', fontFamily: 'Inter-Regular', fontSize: 14, lineHeight: 21, marginTop: 8 },
  offerCode: { minHeight: 66, borderWidth: 1, borderColor: '#D8D2DC', borderRadius: 10, paddingHorizontal: 14, marginTop: 20, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  offerCodeLabel: { color: '#7A7380', fontFamily: 'Inter-Bold', fontSize: 9, letterSpacing: 1.1 },
  offerCodeValue: { color: BRAND_PURPLE, fontFamily: 'Inter-Bold', fontSize: 18, marginTop: 3 },
  offerDone: { minHeight: 48, borderRadius: 8, backgroundColor: BRAND_PURPLE, alignItems: 'center', justifyContent: 'center', marginTop: 14 },
  offerDoneText: { color: '#FFFFFF', fontFamily: 'Inter-SemiBold', fontSize: 14 },
  catalogTop: { width: '100%', maxWidth: 1280, alignSelf: 'center', paddingHorizontal: 20, backgroundColor: '#F9FAFB' },
  loadingGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 16, paddingHorizontal: 20 },
  productSkeleton: { flexBasis: 220, flexGrow: 1, maxWidth: 320, borderRadius: 12, backgroundColor: '#FFFFFF', overflow: 'hidden', paddingBottom: 16 },
  skeletonImage: { width: '100%', height: 180, backgroundColor: '#E8E3EB' },
  skeletonLineWide: { height: 14, width: '72%', borderRadius: 7, backgroundColor: '#E8E3EB', marginTop: 14, marginHorizontal: 12 },
  skeletonLine: { height: 12, width: '42%', borderRadius: 6, backgroundColor: '#F3EFF7', marginTop: 10, marginHorizontal: 12 },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: 16,
    backgroundColor: '#F9FAFB',
  },
  headerTitle: {
    fontSize: 28,
    fontFamily: 'Inter-Bold',
    color: '#1F2937',
  },
  headerSubtitle: { marginTop: 4, fontSize: 13, fontFamily: 'Inter-Regular', color: '#665F6C' },
  hero: {
    marginTop: 20,
    marginBottom: 16,
    height: 320,
    borderRadius: 18,
    overflow: 'hidden',
    backgroundColor: '#2A143C',
  },
  heroImage: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    height: '100%',
  },
  heroImageCutout: {
    position: 'absolute',
    top: 6,
    bottom: 0,
    right: 2,
    width: '66%',
    height: '98%',
  },
  heroContent: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 22,
    paddingTop: 18,
    paddingBottom: 22,
    justifyContent: 'space-between',
  },
  heroTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  heroEyebrow: {
    color: BRAND_GOLD,
    fontFamily: 'Inter-Bold',
    fontSize: 11,
    letterSpacing: 1.6,
  },
  heroFilterButton: {
    width: 38,
    height: 38,
    borderRadius: 10,
    backgroundColor: 'rgba(255,255,255,0.16)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.22)',
  },
  heroTitle: {
    color: '#FFFFFF',
    fontFamily: 'Inter-Bold',
    fontSize: 30,
    lineHeight: 34,
    letterSpacing: -0.5,
  },
  heroSubtitle: {
    color: 'rgba(255,255,255,0.82)',
    fontFamily: 'Inter-Regular',
    fontSize: 14,
    lineHeight: 20,
    marginTop: 10,
    maxWidth: 340,
  },
  heroCount: {
    color: 'rgba(255,255,255,0.6)',
    fontFamily: 'Inter-Medium',
    fontSize: 12,
    marginTop: 14,
  },
  heroActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 18,
  },
  heroPrimaryBtn: {
    backgroundColor: BRAND_GOLD,
    paddingHorizontal: 18,
    paddingVertical: 11,
    borderRadius: 10,
  },
  heroPrimaryBtnText: {
    color: '#2A143C',
    fontFamily: 'Inter-Bold',
    fontSize: 13.5,
  },
  heroSecondaryBtn: {
    paddingHorizontal: 18,
    paddingVertical: 11,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.55)',
    backgroundColor: 'rgba(255,255,255,0.12)',
  },
  heroSecondaryBtnText: {
    color: '#FFFFFF',
    fontFamily: 'Inter-SemiBold',
    fontSize: 13.5,
  },
  trustStrip: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
    marginBottom: 16,
  },
  trustItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  trustCheck: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#F0E9F6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  trustText: {
    fontSize: 12,
    fontFamily: 'Inter-Medium',
    color: '#4B5563',
  },
  salesMomentumCard: {
    maxWidth: 720,
    marginBottom: 16,
    borderRadius: 14,
    padding: 14,
    backgroundColor: '#32154E',
    borderWidth: 1,
    borderColor: 'rgba(253,184,19,0.32)',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    shadowColor: '#32154E',
    shadowOpacity: 0.16,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
  salesMomentumIcon: {
    width: 38,
    height: 38,
    borderRadius: 11,
    backgroundColor: 'rgba(253,184,19,0.14)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  salesMomentumCopy: {
    flex: 1,
  },
  salesMomentumTitle: {
    color: '#FFFFFF',
    fontFamily: 'Inter-Bold',
    fontSize: 14,
  },
  salesMomentumText: {
    color: 'rgba(255,255,255,0.74)',
    fontFamily: 'Inter-Regular',
    fontSize: 12,
    lineHeight: 17,
    marginTop: 3,
  },
  productImageSoldOut: {
    opacity: 0.5,
  },
  soldOutOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  lockOverlay: {
    position: 'absolute',
    top: 0, left: 0, right: 0, bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
    backgroundColor: 'rgba(23,19,28,0.5)',
  },
  lockText: { color: '#FFFFFF', fontFamily: 'Inter-Bold', fontSize: 13, marginTop: 4 },
  lockSub: { color: 'rgba(255,255,255,0.9)', fontFamily: 'Inter-SemiBold', fontSize: 11 },
  soldOutText: {
    color: '#FFFFFF',
    fontFamily: 'Inter-Bold',
    fontSize: 13,
    letterSpacing: 1.5,
    backgroundColor: 'rgba(23,19,28,0.72)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
    overflow: 'hidden',
  },
  lowStockPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    alignSelf: 'flex-start',
    backgroundColor: '#FEF3C7',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    marginTop: 2,
  },
  lowStockText: {
    fontSize: 11,
    fontFamily: 'Inter-SemiBold',
    color: '#B45309',
  },
  rewardHint: {
    marginTop: 6,
    fontSize: 11,
    lineHeight: 15,
    fontFamily: 'Inter-SemiBold',
    color: '#7C3AED',
  },
  swatchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginBottom: 8,
  },
  swatch: {
    width: 13,
    height: 13,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.14)',
  },
  swatchMore: {
    fontSize: 10,
    fontFamily: 'Inter-Medium',
    color: '#9CA3AF',
    marginLeft: 2,
  },
  editorialTitle: {
    fontSize: 20,
    fontFamily: 'Inter-Bold',
    color: '#1F2937',
  },
  editorialSubtitle: {
    fontSize: 13,
    fontFamily: 'Inter-Regular',
    color: '#665F6C',
    marginTop: 2,
    marginBottom: 12,
  },
  lookbookSection: {
    paddingHorizontal: 20,
    marginTop: 4,
    marginBottom: 22,
  },
  recentSection: {
    paddingHorizontal: 20,
    marginBottom: 22,
  },
  recentRow: {
    gap: 12,
    paddingTop: 12,
    paddingRight: 8,
  },
  recentCard: {
    width: 110,
  },
  recentImage: {
    width: 110,
    height: 132,
    borderRadius: 12,
    backgroundColor: '#F3F4F6',
    marginBottom: 6,
  },
  recentName: {
    fontSize: 12,
    fontFamily: 'Inter-Medium',
    color: '#374151',
  },
  recentPrice: {
    fontSize: 12,
    fontFamily: 'Inter-SemiBold',
    color: BRAND_PURPLE,
    marginTop: 2,
  },
  styleMeBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginHorizontal: 20,
    marginBottom: 20,
    padding: 16,
    borderRadius: 14,
    backgroundColor: '#F3EFF7',
    borderWidth: 1,
    borderColor: '#E6DDEF',
  },
  styleMeIcon: {
    width: 42,
    height: 42,
    borderRadius: 10,
    backgroundColor: BRAND_PURPLE,
    alignItems: 'center',
    justifyContent: 'center',
  },
  styleMeTitle: {
    fontSize: 16,
    fontFamily: 'Inter-Bold',
    color: '#17131C',
  },
  styleMeCopy: {
    fontSize: 12.5,
    fontFamily: 'Inter-Regular',
    color: '#665F6C',
    marginTop: 3,
    lineHeight: 17,
  },
  lookbookRow: {
    gap: 12,
    paddingRight: 8,
  },
  lookbookCard: {
    width: 250,
    height: 175,
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: '#EDEAF0',
  },
  lookbookImage: {
    width: '100%',
    height: '100%',
  },
  lookbookOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 82,
  },
  lookbookLabel: {
    position: 'absolute',
    left: 14,
    bottom: 12,
    color: '#FFFFFF',
    fontFamily: 'Inter-Bold',
    fontSize: 16,
    letterSpacing: 0.3,
  },
  communitySection: {
    width: '100%',
  },
  communityRow: {
    gap: 10,
    paddingRight: 8,
  },
  communityImage: {
    width: 128,
    height: 168,
    borderRadius: 12,
    backgroundColor: '#EDEAF0',
  },
  headerActions: {
    flexDirection: 'row',
    gap: 8,
  },
  filterButton: {
    width: 40,
    height: 40,
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E8E3EB',
  },
  searchContainer: {
    marginBottom: 14,
    maxWidth: 720,
  },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    paddingHorizontal: 16,
    height: 48,
    borderWidth: 1,
    borderColor: '#D8D2DC',
  },
  searchInput: {
    flex: 1,
    marginLeft: 12,
    fontSize: 16,
    fontFamily: 'Inter-Regular',
    color: '#1F2937',
  },
  categoriesContainer: {
    marginBottom: 18,
    zIndex: 1,
    paddingTop: 2,
    paddingBottom: 2,
    backgroundColor: '#F9FAFB',
  },
  categoriesContent: {
    paddingVertical: 4,
    gap: 8,
  },
  catTilesContent: { paddingHorizontal: 16, gap: 16, paddingVertical: 6, alignItems: 'flex-start' },
  catTile: { alignItems: 'center', width: 66 },
  catImgWrap: { width: 62, height: 62, borderRadius: 31, overflow: 'hidden', backgroundColor: '#F3F4F6', borderWidth: 2, borderColor: 'transparent' },
  catImgWrapActive: { borderColor: BRAND_PURPLE },
  catImg: { width: '100%', height: '100%' },
  catImgFallback: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: '#EDEAF0' },
  catImgFallbackText: { fontFamily: 'Inter-Bold', fontSize: 22, color: BRAND_PURPLE },
  catLabel: { fontSize: 11, fontFamily: 'Inter-Medium', color: '#665F6C', marginTop: 6, textAlign: 'center', width: 66 },
  catLabelActive: { color: BRAND_PURPLE, fontFamily: 'Inter-Bold' },
  categoryChip: {
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 7,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    minHeight: 40,
    alignItems: 'center',
  },
  categoryChipActive: {
    backgroundColor: BRAND_PURPLE,
    borderColor: BRAND_PURPLE,
  },
  categoryText: {
    fontSize: 14,
    fontFamily: 'Inter-Medium',
    color: '#6B7280',
  },
  categoryTextActive: {
    color: '#FFFFFF',
  },
  productCard: {
    flex: 1,
    width: '100%',
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    overflow: 'hidden',
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#E8E3EB',
  },
  hotBadge: {
    position: 'absolute',
    zIndex: 2,
    top: 10,
    right: 0,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: BRAND_GOLD,
    borderTopLeftRadius: 12,
    borderBottomLeftRadius: 12,
  },
  hotBadgeText: {
    color: BRAND_PURPLE,
    fontFamily: 'Inter-Bold',
    fontSize: 10,
    letterSpacing: 0.8,
  },
  saleBadge: { backgroundColor: '#C92A2A' },
  saleBadgeText: { color: '#FFFFFF' },
  wishlistButton: { position: 'absolute', zIndex: 4, top: 10, left: 10, width: 42, height: 42, borderRadius: 21, backgroundColor: 'rgba(255,255,255,0.94)', alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#E8E3EB' },
  productImage: {
    width: '100%',
    aspectRatio: 0.86,
    backgroundColor: '#F3F4F6',
  },
  productInfo: {
    padding: 12,
  },
  productName: {
    fontSize: 14,
    fontFamily: 'Inter-SemiBold',
    color: '#1F2937',
    marginBottom: 4,
    lineHeight: 18,
  },
  productSubtitle: {
    fontSize: 11,
    fontFamily: 'Inter-Medium',
    color: '#6B7280',
    marginBottom: 6,
    marginTop: -1,
  },
  productDescription: {
    fontSize: 12,
    fontFamily: 'Inter-Regular',
    color: '#6B7280',
    marginBottom: 6,
    lineHeight: 16,
  },
  categoriesRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
    marginBottom: 8,
  },
  categoryBadge: {
    fontSize: 10,
    fontFamily: 'Inter-Medium',
    color: BRAND_PURPLE,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  productMeta: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  cardPriceRow: { flexDirection: 'row', alignItems: 'center', gap: 6, flexWrap: 'wrap' },
  cardComparePrice: { fontSize: 12, fontFamily: 'Inter-Regular', color: '#9CA3AF', textDecorationLine: 'line-through' },
  cardDiscountBadge: { backgroundColor: '#EF4444', borderRadius: 5, paddingHorizontal: 5, paddingVertical: 1 },
  cardDiscountText: { color: '#FFFFFF', fontFamily: 'Inter-Bold', fontSize: 10 },
  productPrice: {
    fontSize: 16,
    fontFamily: 'Inter-Bold',
    color: BRAND_PURPLE,
  },
  ratingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  ratingText: {
    fontSize: 12,
    fontFamily: 'Inter-Medium',
    color: '#6B7280',
  },
  productVariants: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  sizesContainer: {
    flexDirection: 'row',
    gap: 4,
  },
  sizeText: {
    fontSize: 10,
    fontFamily: 'Inter-Medium',
    color: '#9CA3AF',
    backgroundColor: '#F3F4F6',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  moreText: {
    fontSize: 10,
    fontFamily: 'Inter-Medium',
    color: BRAND_PURPLE,
  },
  stockInfo: {
    alignItems: 'flex-end',
  },
  stockText: {
    fontSize: 10,
    fontFamily: 'Inter-Medium',
    color: '#10B981',
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 40,
  },
  emptyText: {
    fontSize: 16,
    fontFamily: 'Inter-Regular',
    color: '#6B7280',
    textAlign: 'center',
  },

  // Modal styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalScrollContainer: {
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 20,
  },
  modalContent: {
    marginHorizontal: 20,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 24,
    width: '90%',
    maxWidth: 400,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 8,
  },
  modalTitle: {
    fontSize: 20,
    fontFamily: 'Inter-Bold',
    color: '#1F2937',
    marginBottom: 24,
    textAlign: 'center',
  },

  // Filter styles
  filterLabel: {
    fontSize: 16,
    fontFamily: 'Inter-SemiBold',
    color: '#1F2937',
    marginBottom: 12,
    marginTop: 16,
  },
  filterGroup: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 16,
  },
  filterChip: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    backgroundColor: '#F9FAFB',
  },
  filterChipActive: {
    backgroundColor: BRAND_PURPLE,
    borderColor: BRAND_PURPLE,
  },
  filterChipText: {
    fontSize: 14,
    fontFamily: 'Inter-Medium',
    color: '#6B7280',
  },
  filterChipTextActive: {
    color: '#FFFFFF',
  },

  // Price input styles
  priceInputs: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 16,
  },
  priceInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    fontFamily: 'Inter-Regular',
    color: '#1F2937',
    backgroundColor: '#F9FAFB',
  },

  // Button styles
  modalActions: {
    marginTop: 24,
    gap: 12,
  },
  applyButton: {
    backgroundColor: BRAND_PURPLE,
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: 'center',
  },
  applyButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontFamily: 'Inter-SemiBold',
  },
  clearButton: {
    backgroundColor: '#F3F4F6',
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  clearButtonText: {
    color: '#1F2937',
    fontSize: 16,
    fontFamily: 'Inter-SemiBold',
  },
});
